import React from "react";

export const MyProjects = [
  {
    id: "1",
    projectTitle: "Register data",
    category: ["node", "bootstrap"],
    image: "./image/register.PNG",
    description: "A website to record customer data using CRUD operations. Data can be added, updated, viewed and deleted using nodejs, express and mongoDB.",
    link: "https://register-customer-data.onrender.com",
    github:
      "https://github.com/AbdallahAmr777/Register-customer-data/tree/master",
  },
  {
    id: "2",
    projectTitle: "Movie App",
    category: ["react"],
    image: "./image/Capture9.PNG",
    description: "A website that uses react and fatchAPI. The idea is that we search a movie and add it to the Watchlist, and from there we can delete the movie or transfer it to the Watched List. ",
    link: "https://movies-movies.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Movies",
  },
  {
    id: "3",
    projectTitle: "Shopping Card",
    category: ["react"],
    image: "./image/Capture5.PNG",
    description: "A website that is part of ecommerce using react and multiple functions. The idea is that it adds a product to the cart and can delete it and calculate the price of all items.",
    link: "https://shoping-cart-pi.vercel.app/",
    github: "https://github.com/AbdallahAmr777/shoping_cart",
  },
  {
    id: "4",
    projectTitle: "Amazon-Clone",
    category: ["React"],
    image: "./image/amazon.PNG",
    description: "Designing the Amazon website, adding products to the cart, filtering and deleting products, using reactjs",
    link: "https://amazonn-chi.vercel.app/",
    github: "https://github.com/AbdallahAmr777/amazonn",
  },
  {
    id: "5",
    projectTitle: "Portfolio",
    category: ["react"],
    image: "./image/Capture6.PNG",
    description: "Portfolio using react, animation, page loading, projects section, and contact us section",
    link: "https://abdallahamr.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Abdallahamr",
  },
  {
    id: "6",
    projectTitle: "Text to Speech",
    category: ["js", "css"],
    image: "./image/speech.PNG",
    description: "Text To Speech (TTS) is a technology that enables your text to be converted into speech sounds. In this project (Text To Speech Converter App), you can convert",
    link: "https://text-to-speech-liard.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Text-to-Speech",
  },
  {
    id: "7",
    projectTitle: "Netflix Clone",
    category: ["css", "bootstrap", "js"],
    image: "./image/Capture10.PNG",
    description: "Netflix Design page And the validation form page, and after passing it, a movie page is displayed with the fatchAPI",
    github: "https://github.com/AbdallahAmr777/Netflix",
  },
  {
    id: "8",
    projectTitle: "Watch Shope",
    category: ["css", "bootstrap"],
    image: "./image/Capture3.PNG",
    description: "Watch shope design with html ,css and bootstrap",
    link: "https://watches-ashy.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Watches",
  },
  {
    id: "9",
    projectTitle: "Bootstrap Project",
    category: ["bootstrap"],
    image: "./image/Capture4.PNG",
    description: "Design with bootstrap responsive to all screens",
    link: "https://nouvill.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Nouvill",
  },
  {
    id: "10",
    projectTitle: "Restaurant",
    category: ["css"],
    image: "./image/Capture.PNG",
    description: "Restaurant use HTML , CSS and animation ,responsive to all screens",
    link: "https://restaurant-snowy-chi.vercel.app/",
    github: "https://github.com/AbdallahAmr777/restaurant",
  },
  {
    id: "11",
    projectTitle: "Portfolio",
    category: ["css"],
    image: "./image/Capture2.PNG",
    description: "Using HTML and CSS for the front-end ,responsive to all screens",
    link: "https://abdullah-amr.vercel.app/",
    github: "https://github.com/AbdallahAmr777/AbdullahAmr",
  },
  {
    id: "12",
    projectTitle: "Landing Page",
    category: ["react"],
    image: "./image/Capture.8.PNG",
    description: "Using HTML and CSS and Javascript and React for the front-end responsive to all screens",
    link: "https://landing-landing-three.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Landing",
  },

];
