export const MyProjects = [
  {
    id: "1",
    projectTitle: "Movie App",
    category: ["react"],
    image: "./image/Capture9.PNG",
    description: "",
    link: "https://movies-movies.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Movies",
  },
  {
    id: "2",
    projectTitle: "Portfolio",
    category: ["react"],
    image: "./image/Capture6.PNG",
    description: "",
    link: "https://abdallahamr.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Abdallahamr",
  },
  {
    id: "3",
    projectTitle: "Netflix Clone",
    category: ["css", "bootstrap", "js"],
    image: "./image/Capture10.PNG",
    description: "",
    link: "https://netflix-9le7.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Netflix",
  },
  {
    id: "4",
    projectTitle: "Shopping Card",
    category: ["react"],
    image: "./image/Capture5.PNG",
    description: "",
    link: "https://shoping-cart-pi.vercel.app/",
    github: "https://github.com/AbdallahAmr777/shoping_cart",
  },
  {
    id: "5",
    projectTitle: "Bootstrap Project",
    category: ["bootstrap"],
    image: "./image/Capture4.PNG",
    description: "",
    link: "https://nouvill.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Nouvill",
  },
  {
    id: "6",
    projectTitle: "Watch Shope",
    category: ["css", "bootstrap"],
    image: "./image/Capture3.PNG",
    description: "",
    link: "https://watches-ashy.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Watches",
  },
  {
    id: "7",
    projectTitle: "Restaurant",
    category: ["css"],
    image: "./image/Capture.PNG",
    description: "",
    link: "https://restaurant-snowy-chi.vercel.app/",
    github: "https://github.com/AbdallahAmr777/restaurant",
  },
  {
    id: "8",
    projectTitle: "",
    category: ["css"],
    image: "./image/Capture2.PNG",
    description: "",
    link: "",
    github: "",
  },
  {
    id: "9",
    projectTitle: "Landing Page",
    category: ["react"],
    image: "./image/Capture.8.PNG",
    description: "",
    link: "https://landing-landing-three.vercel.app/",
    github: "https://github.com/AbdallahAmr777/Landing",
  },
  // {
  //   id: "",
  //   projectTitle: "",
  //   category: [],
  //   image: "",
  //   description: "",
  //   link: "",
  //   github: "",
  // },

];
